
title: Kevin Ma
email: kym5@cornell.edu
description: Kevin Ma
baseurl: "" 
twitter_username: messybin
github_username:  kevinyma
email: kym5@cornell.edu

sass:
  sass_dir: _sass
collections: 
  projects:
    output: true
    permalink: /made/:path/
include: ['_pages']
markdown: kramdown
