
title: Kevin
email: kym5@cornell.edu
description: Kevin Ma's fun box of fun things.
baseurl: "" 
twitter_username: messybin
github_username:  kevinyma
email: kym5@cornell.edu

sass:
  sass_dir: _sass
collections: 
  projects:
    output: true
    permalink: /made/:path/
include: ['_pages']
markdown: kramdown
