# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kevin Ma
email: kym5@cornell.edu
description: Kevin Ma
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kevinyma.github.io" # the base hostname & protocol for your site
twitter_username: messybin
github_username:  kevinyma
email: kym5@cornell.edu
# Build settings
sass:
  sass_dir: _sass
collections: 
  projects:
    output: true
    permalink: /made/:path/
include: ['_pages']
markdown: kramdown
