
title: Kevin Ma
email: kym5@cornell.edu
description: Kevin's emporium of fun things.
baseurl: "" 
twitter_username: messybin
github_username:  kevinyma
email: kym5@cornell.edu

sass:
  sass_dir: _sass
collections: 
  projects:
    output: true
    permalink: /makes/:path/
  misc:
    output: true
    permalink: /:path/
include: ['_pages']
markdown: kramdown
